services:
  db:
    image: postgres:16-alpine
    env_file: .env.development
    ports: [5432:5432]
    networks: [spring-network]
    volumes: [data:/var/lib/postgresql/data]

  backend:
    build:
      context: .
    env_file: .env.development
    ports: [8080:8080]
    depends_on: [db]
    networks: [spring-network]

  frontend:
    build:
      context: frontend
    ports: [80:80]
    depends_on: [backend]

networks:
  spring-network:
    driver: bridge

volumes:
  data:
