services:
  db:
    image: postgres:16-alpine
    env_file: .env
    ports: [5432:5432]
    networks: [spring-network]
    volumes: [data:/var/lib/postgresql/data]

  app:
    build:
      context: .
    env_file: .env
    ports: [80:80]
    depends_on: [db]
    networks: [spring-network]

networks:
  spring-network:
    driver: bridge

volumes:
  data:
